chore(deps): update dependencies
openfga/cli pull request #246
Opened 2024-02-01 19:50 UTC by evansims

## Description

This PR updates `go.mod` and the `go.sum` dependencies lockfile to use the latest versions.

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2024-02-01 20:16 UTC, rhamzeh approved these changes

2024-02-01 20:18 UTC, rhamzeh requested changes
@evansims make sure to update the api in language and openfga first then update them all together here - we've had problems in the past when CLI has different versions of the API than those

2024-02-01 20:21 UTC, evansims commented
@rhamzeh Thanks for the heads up! I have PRs for both of those here:
- https://github.com/openfga/openfga/pull/1333
- https://github.com/openfga/language/pull/143

2024-02-06 21:57 UTC, evansims commented
@rhamzeh 👋 Should be good to go on this now

2024-02-06 22:17 UTC, rhamzeh approved these changes

2024-02-06 22:21 UTC, merged