fix: properly exit on errors
openfga/cli pull request #63
Opened 2023-07-08 01:06 UTC by rhamzeh

## Description

<img width="461" alt="Screenshot 2023-07-05 at 11 43 15 AM" src="https://github.com/openfga/cli/assets/536147/63bf09f6-210c-419c-b84b-efebf450d67b">

## References

closes #62 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-07-08 01:44 UTC, adriantam requested changes

2023-07-08 01:44 UTC, adriantam commented on cmd/tuple/changes.go
> +	Example: "fga tuple changes --store-id=01H0H015178Y2V4CX10C2KGHF4 document",
is this right?
Should it be 
```
fga tuple changes --store-id=01H0H015178Y2V4CX10C2KGHF4 --type=document
```

Also need to fix REAMDE

2023-07-10 13:44 UTC, jpadilla approved these changes

2023-07-10 14:11 UTC, adriantam approved these changes

2023-07-10 14:12 UTC, merged